Fixed the code after review

diff --git a/tests/golden/openshift4/crossplane/crossplane/02_upgrade/00_upgrade.yaml b/tests/golden/openshift4/crossplane/crossplane/02_upgrade/00_upgrade.yaml
--- a/tests/golden/openshift4/crossplane/crossplane/02_upgrade/00_upgrade.yaml
+++ b/tests/golden/openshift4/crossplane/crossplane/02_upgrade/00_upgrade.yaml
@@ -94,18 +94,19 @@ spec:
             - -eu
             - -c
             - "#!/bin/bash\nset -e\n\n#Patch CRDS so that ArgoCD does not delete them\
-              \ during upgrade\nfor crd in $CRDS_TO_PATCH; do\n\t  exists=$(kubectl\
-              \ get crd \"${crd}\" --ignore-not-found)\n    if [ -z \"$exists\" ];\
-              \ then\n      >&2 echo \"WARNING: Skipping '${crd}': not found.\"\n\
-              \      continue\n    fi\n    #Remove ArgoCD managed-by label from the\
-              \ CRD\n    kubectl label crd \"${crd}\" argocd.argoproj.io/instance-\n\
-              done\n\n#Locks are not managed anymore in the helm chart therefore remove\
-              \ them from ArgoCD sync cycle\nfor lock in $(kubectl get locks -o name);\
-              \ do\n    #Remove ArgoCD managed-by label from the Lock\n    kubectl\
-              \ label \"$lock\" argocd.argoproj.io/instance-\ndone\n\n#Patch providers\
-              \ so that ArgoCD does not delete them during upgrade\nfor provider in\
-              \ $(kubectl get providers -o name); do\n    #Annotate ArgoCD sync-options\n\
-              \    kubectl annotate \"$provider\" --overwrite argocd.argoproj.io/sync-options=Prune=false\n\
+              \ during upgrade\nfor crd in $CRDS_TO_PATCH; do\nif ! kubectl get crd\
+              \ \"${crd}\" > /dev/null 2>&1; then\n  >&2 echo \"WARNING: Skipping\
+              \ 'blah': not found.\"\n  continue\nfi\n    if [ -z \"$exists\" ]; then\n\
+              \      >&2 echo \"WARNING: Skipping '${crd}': not found.\"\n      continue\n\
+              \    fi\n    #Remove ArgoCD managed-by label from the CRD\n    kubectl\
+              \ label crd \"${crd}\" argocd.argoproj.io/instance-\ndone\n\n#Locks\
+              \ are not managed anymore in the helm chart therefore remove them from\
+              \ ArgoCD sync cycle\nfor lock in $(kubectl get locks -o name); do\n\
+              \    #Remove ArgoCD managed-by label from the Lock\n    kubectl label\
+              \ \"$lock\" argocd.argoproj.io/instance-\ndone\n\n#Patch providers so\
+              \ that ArgoCD does not delete them during upgrade\nfor provider in $(kubectl\
+              \ get providers -o name); do\n    #Annotate ArgoCD sync-options\n  \
+              \  kubectl annotate \"$provider\" --overwrite argocd.argoproj.io/sync-options=Prune=false\n\
               done\n\n#Patch configurations so that ArgoCD does not delete them during\
               \ upgrade\nfor configuration in $(kubectl get configurations -o name);\
               \ do\n    #Annotate ArgoCD sync-options\n    kubectl annotate \"$configuration\"\
